import type { Metadata } from 'next';
import './styles/globals.css';
import vazirFont from '@/constans/localFonts';
import Header from '@/app/components/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl'>
      <body className={`${vazirFont.variable} font-sans  min-h-screen`}>
        <Header />
        <div className='container xl:max-w-7xl '>{children}</div>
      </body>
    </html>
  );
}
