import type { Metadata } from 'next';
import './styles/globals.css';
import vazirFont from '@/constans/localFonts';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='fa' dir='rtl' className={`${vazirFont.variable} font-sans`}>
      <body>{children}</body>
    </html>
  );
}
